---

#
# RabbitMQ Essential Information
# Default Port: 5672
#
# Management Plugin
# rabbitmq-plugins enable rabbitmq_management
# Management Port: 15672
# curl -i -u guest:guest http://[HOST]:15672/api/whoami
#

#################################
##### RabbitMQ Repositories #####
#################################

- name: Authorize the package signing key for RabbitMQ
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

# (2015-07-26): Default is v3.2.4-1 instead of current v3.5.4-1
- name: Add RabbitMQ Repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present update_cache=yes

#############################
##### RabbitMQ Packages #####
#############################

- name: Ensure RabbitMQ is present
  apt: pkg=rabbitmq-server state=latest

- name: Ensure RabbitMQ is started
  service: name=rabbitmq-server state=started enabled=yes

##################################
##### RabbitMQ Configuration #####
##################################

- name: List RabbitMQ Plugins
  command: rabbitmq-plugins list
  changed_when: False
  register: rabbitmq_plugins

- name: Ensure RabbitMQ Management Plugin
  command: rabbitmq-plugins enable rabbitmq_management
  # "*" added as of v3.5.4-1 or earlier (not default v3.2.4-1)
  # The "*" shows as a space in terminal for some reason.
  when: rabbitmq_plugins.stdout.find("[E*] rabbitmq_management") == -1
  notify: RabbitMQ Restart

# Ensure that the VHost exists
- rabbitmq_vhost: name={{ rabbitmq_vhost }} state=present

# Manual
# http://stackoverflow.com/questions/14699873/how-to-reset-user-for-rabbitmq-management
# add_user newadmin s0m3p4ssw0rd
# set_permissions new_admin ".*" ".*" ".*"
# sudo rabbitmqctl set_user_tags newadmin administrator
# sudo rabbitmqctl list_users
- name: Add RabbitMQ Admin User
  rabbitmq_user: user={{ rabbitmq_username }}
                 password={{ rabbitmq_password }}
                 vhost={{ rabbitmq_vhost }}
                 tags=administrator
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Add RabbitMQ Code User
  rabbitmq_user: user={{ rabbitmq_username }}
                 password={{ rabbitmq_password }}
                 vhost={{ rabbitmq_vhost }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
